version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: bacefook-postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: bacefook-api
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    command: sh -c "npx prisma migrate deploy && npm run start"

volumes:
  pgdata: